"""add_trigger_focus_on_and_task_trigger_id

Revision ID: 1078fc83ad4e
Revises: add_locked_at
Create Date: 2026-06-10 21:43:29.323839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1078fc83ad4e'
down_revision: Union[str, Sequence[str], None] = 'add_locked_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('trigger_id', sa.UUID(), nullable=True))
    op.add_column('triggers', sa.Column('focus_on', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triggers', 'focus_on')
    op.drop_column('tasks', 'trigger_id')
    # ### end Alembic commands ###
