"""initial

Revision ID: 2e8f9b469eab
Revises: 
Create Date: 2026-06-03 20:59:22.912348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8f9b469eab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('analysis_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('trade_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('feedback_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('tasks_raw_info_id_key'), 'tasks', type_='unique')
    op.drop_column('tasks', 'trade_id')
    op.drop_column('tasks', 'analysis_id')
    op.drop_column('tasks', 'feedback_id')
    op.create_index(op.f('ix_triggers_status'), 'triggers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triggers_status'), table_name='triggers')
    op.add_column('tasks', sa.Column('feedback_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('tasks_raw_info_id_key'), 'tasks', ['raw_info_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tasks', 'feedback_ids')
    op.drop_column('tasks', 'trade_ids')
    op.drop_column('tasks', 'analysis_ids')
    # ### end Alembic commands ###
